/**
 * `@bedrock-core/server-runtime` — the bedrock-core server runtime.
 *
 * Addons register their identity + base data with the runtime, which flows into a
 * cross-addon registry built on `@bedrock-core/sync`. Typical usage:
 *
 * ```ts
 * import { core } from '@bedrock-core/server-runtime';
 * import translationKeys from '@bedrock-core/generated/translation-keys';
 * import guides from '@bedrock-core/generated/guides';
 *
 * // register() brings the addon online — there is no separate start(). Everything the
 * // addon declares rides in the one call; translations/guide/config are all optional.
 * const config = core.register({
 *   creator: 'bt',                 // creator/vendor id, lowercase a-z0-9_
 *   pack: 'gc_shop',               // abbreviated pack id — together: namespace `bt_gc_shop`
 *   packName: 'My Cool Shop',      // display label only
 *   version: '1.2.0',
 *   dependencies: ['os_economy'],                     // namespaces (`creator_pack`)
 *   optionalDependencies: ['os_leaderboards'],
 *   translations: translationKeys, // generated by-locale keys, shared with other addons' UIs
 *   guide: guides,                 // compiled guide manifest from the guides filter
 *   config: { server: { taxRate: { type: 'number', default: 0.05, min: 0, max: 1, label: 'Tax Rate' } } },
 * });
 *
 * config.server.get().taxRate;     // typed accessors, same as core.config.define()'s return
 * core.registry.onRegister(addon => console.warn('registered', addon.id));
 * core.registry.onNamespaceCollision(info => console.error('collision', info.id));
 * core.features.add('leaderboard-sync', {
 *   condition: r => r.has('os_leaderboards'),
 *   onEnable() { console.warn('leaderboards available'); },
 *   onDisable() { console.warn('leaderboards gone'); },
 * });
 * core.rpc.onRequest('buy', params => purchase(params));
 * core.state.set('price', 10);   // namespace pre-filled from core.namespace
 * ```
 */
export { Runtime, core } from './runtime';
export type { RegisterOptions } from './runtime';

export { RUNTIME_VERSION } from './runtime-version';

export { compareVersions } from './version';

export { HostElection } from './host';
export type { HostListener } from './host';

export { Registry } from './registry';
export type { RegisteredAddon, AddonListener, CollisionListener } from './registry';

export { FeatureManager } from './features';
export type { FeatureSpec, FeatureConditionContext, TypedFeatureAccessor } from './features';

export { ScopedState, RESERVED_STATE_PREFIX, isReservedStateKey } from './scoped-state';

export { addonNamespace, validateManifest } from './manifest';
export type { AddonManifest, ManifestMeta } from './manifest';

export type { TypedClient, RPCHandlerMap } from '@bedrock-core/sync';

export { TranslationsRegistry } from './translations';
export type { TranslationsChangeListener, TranslationKeysMap, TranslationKeysByLocale } from './translations';

export { GuidesRegistry } from './guides/guides-registry';
export type { GuidesChangeListener } from './guides/guides-registry';
export type { GuideManifest } from './guides/types';

export { ConfigRegistry } from './config/config-registry';
export type { Config, ConfigAccessOptions, LocalConfigScopes, RemoteConfigAccessor, TypedRemoteConfig } from './config/config-registry';
export { denyReason, isOperator } from './config/authorization';
export type { ConfigScopeName } from './config/authorization';
export { EntityConfigScope } from './config/scopes';
export { ServerConfigScope } from './config/scopes';
export type {
  ConfigDefinition,
  ConfigEntry,
  ConfigValue,
  BooleanEntry,
  NumberEntry,
  StringEntry,
  EnumEntry,
  ListEntry,
  FlatSchema,
  SerializedEntry,
  SchemaToValue,
  DotPath,
  PathValue,
  DeepPartial,
} from './config/schema';
