/**
 * Cross-addon translation-key sync (by-locale).
 *
 * Registry display fields (`name`, `description`, `creatorName`) ARE translation keys
 * shipped in each addon's own RP `texts/*.lang`. In-game, Bedrock merges every installed
 * pack's .lang into one world-wide table, so any addon's key resolves at display time.
 * The ui-runtime layout engine, however, measures text server-side from the pack-local
 * `translationKeys.generated.json` — another addon's keys are not in it, so word-wrap/
 * ellipsis metrics would be computed on the raw key string.
 *
 * This service closes that gap. The `translation-keys` Regolith filter now emits a
 * BY-LOCALE map (`Record<locale, Record<key, string>>`, i.e. `TranslationKeysByLocale`):
 * every configured locale's key -> resolved-string table ships in one module because
 * Bedrock script bundles are static (no per-player dynamic import). Each addon publishes
 * that full map (`@bedrock-core/generated/translation-keys`) to replicated state; the
 * registry then merges every addon's map PER LOCALE — repeated keys are simply overridden,
 * mirroring how Bedrock's world-level .lang merge behaves.
 *
 * At render time you want ONE flat locale map for `TranslationKeysContext`:
 * - `forLocale(locale)` merges every addon's table for that single locale (cached per locale).
 * - `forPlayer(player)` picks the player's client locale when any addon authored it, else the
 *   default locale, else any available locale, then returns that merged flat map.
 * - `all()` is the default-locale (`en_US`) back-compat view — equivalent to `forLocale('en_US')`.
 *
 * ```ts
 * import translationKeys from '@bedrock-core/generated/translation-keys'; // TranslationKeysByLocale
 *
 * core.register({ ..., translations: translationKeys });
 *
 * // In the UI root, per connecting player:
 * <TranslationKeysContext value={core.translations.forPlayer(player)}>
 * ```
 *
 * Late joiners are covered by sync's state snapshot exchange.
 */
import { stateKey } from '@bedrock-core/sync';
import type { State, Unsubscribe } from '@bedrock-core/sync';
import type { Player } from '@minecraft/server';

/** Key -> resolved display string, for ONE locale. */
export type TranslationKeysMap = Record<string, string>;
/** Locale code (e.g. `"en_US"`) -> {@link TranslationKeysMap}. */
export type TranslationKeysByLocale = Record<string, TranslationKeysMap>;

/** Locale assumed for the `all()` back-compat view and the flat-map defensive wrap. */
const DEFAULT_LOCALE = 'en_US';

/**
 * State key each addon publishes its by-locale map under (namespace = the addon's transport id).
 * The address string is unchanged from the pre-by-locale design; only the payload type changed,
 * and `publishedByLocale` defensively wraps any un-migrated flat payload.
 */
const TRANSLATIONS_STATE_KEY = stateKey<TranslationKeysByLocale>('bc-i18n/keys');

export type TranslationsChangeListener = () => void;

export class TranslationsRegistry {
  private readonly _state: State;
  private readonly _addonId: string;
  private readonly _listeners = new Set<TranslationsChangeListener>();
  private readonly _disposers: Unsubscribe[] = [];
  /** Merged flat map cache, keyed by locale; cleared whenever any addon re-publishes. */
  private readonly _byLocale = new Map<string, TranslationKeysMap>();

  constructor(state: State, addonId: string) {
    this._state = state;
    this._addonId = addonId;
  }

  start(): void {
    this._disposers.push(
      this._state.onChange((change) => {
        if (change.key !== TRANSLATIONS_STATE_KEY) { return; }

        this._byLocale.clear();
        this.emitChange();
      }),
    );
  }

  stop(): void {
    for (const dispose of this._disposers.splice(0)) { dispose(); }

    this._listeners.clear();
    this._byLocale.clear();
  }

  /**
   * Publish this addon's translation keys — the full generated BY-LOCALE map — to replicated
   * state so every addon can resolve them. Usually declared up front via
   * `core.register({ translations })`; call directly to publish late or replace the map.
   */
  provide(byLocale: TranslationKeysByLocale): void {
    this._state.set(this._addonId, TRANSLATIONS_STATE_KEY, byLocale);
  }

  /**
   * The merged key -> resolved-string map for a SINGLE locale, across every addon that called
   * `provide()` (including this one). Repeated keys are overridden by whichever addon is merged
   * later — values only differ where a pack deliberately overrides another's key, mirroring
   * Bedrock's own world-level .lang merge. Reads are local-mirror only; the per-locale result is
   * cached and rebuilt when any addon re-publishes. Treat it as read-only.
   */
  forLocale(locale: string): TranslationKeysMap {
    const cached = this._byLocale.get(locale);

    if (cached) { return cached; }

    const merged: TranslationKeysMap = {};

    for (const ns of this._state.namespaces()) {
      Object.assign(merged, this.publishedByLocale(ns)[locale] ?? {});
    }

    this._byLocale.set(locale, merged);

    return merged;
  }

  /**
   * Resolve the merged flat map for a specific player. Picks the player's client locale
   * (`player.clientSystemInfo.locale`) when any addon authored it, otherwise `defaultLocale`,
   * otherwise the first locale any addon published. Returns `{}` when no addon has published
   * anything — mirroring how a missing key already falls back to rendering the literal key.
   */
  forPlayer(player: Player, defaultLocale = DEFAULT_LOCALE): TranslationKeysMap {
    const locale = player.clientSystemInfo.locale;
    const available = this.availableLocales();
    const chosen = [locale, defaultLocale].find(candidate => available.has(candidate)) ?? this.firstOf(available);

    if (chosen === undefined) { return {}; }

    return this.forLocale(chosen);
  }

  /**
   * BACK-COMPAT: the merged flat map for the default locale (`en_US`) — equivalent to
   * `forLocale('en_US')`. Retained so external addons written against the pre-by-locale API keep
   * working; prefer `forPlayer(player)` (per-player locale) or `forLocale(locale)` for new code.
   */
  all(): TranslationKeysMap {
    return this.forLocale(DEFAULT_LOCALE);
  }

  /** The full BY-LOCALE map another addon published, or `{}` if it hasn't. Local-mirror read. */
  of(addonId: string): TranslationKeysByLocale {
    return this.publishedByLocale(addonId);
  }

  /** Notified when any addon's published keys change (coarse — rebuild via `forLocale`/`forPlayer`). */
  onChange(listener: TranslationsChangeListener): Unsubscribe {
    this._listeners.add(listener);

    return (): void => {
      this._listeners.delete(listener);
    };
  }

  /** Every locale any addon has published, across all namespaces. */
  private availableLocales(): Set<string> {
    const locales = new Set<string>();

    for (const ns of this._state.namespaces()) {
      for (const locale of Object.keys(this.publishedByLocale(ns))) { locales.add(locale); }
    }

    return locales;
  }

  private firstOf(locales: Set<string>): string | undefined {
    for (const locale of locales) { return locale; }

    return undefined;
  }

  /**
   * The by-locale map an addon published under this namespace, or `{}` if none/invalid.
   * Defensive back-compat: an un-migrated addon may still publish the old FLAT shape
   * (`Record<string, string>`); detect that (all values are strings) and wrap it as
   * `{ [DEFAULT_LOCALE]: flat }` so mixed fleets still resolve. Otherwise keep only the
   * entries that are themselves nested `Record<string, string>` objects.
   */
  private publishedByLocale(ns: string): TranslationKeysByLocale {
    const value = this._state.get(ns, TRANSLATIONS_STATE_KEY);

    if (!isRecord(value)) { return {}; }

    if (isFlatMap(value)) { return { [DEFAULT_LOCALE]: value }; }

    const result: TranslationKeysByLocale = {};

    for (const [locale, entry] of Object.entries(value)) {
      if (isFlatMap(entry)) { result[locale] = entry; }
    }

    return result;
  }

  private emitChange(): void {
    for (const listener of this._listeners) { listener(); }
  }
}

/** True for any non-null, non-array object. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * True when `value` is a flat locale table: a record whose every value is a string. An empty
 * record qualifies (nothing contradicts it) and wrapping it as one empty default-locale table
 * is harmless. Narrows to {@link TranslationKeysMap} so callers avoid an `as` cast.
 */
function isFlatMap(value: unknown): value is TranslationKeysMap {
  if (!isRecord(value)) { return false; }

  for (const entry of Object.values(value)) {
    if (typeof entry !== 'string') { return false; }
  }

  return true;
}
